version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: reddit-clone-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: reddit_clone
      POSTGRES_PASSWORD: reddit_clone
      POSTGRES_USER: reddit_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: reddit-clone-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.8-alpine
    container_name: reddit-clone-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/data

  server:
    build:
      context: "."
    container_name: reddit-clone-server
    environment:
      DEBUG: "false"
      CELERY_BROKER: amqp://guest:guest@localhost:5672//
      CELERY_BACKEND: redis://localhost:6379
      DATABASE_URL: postgresql+asyncpg://reddit_clone:reddit_clone@db:5432/reddit_clone
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 25
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SENDER:
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  celery:
    build:
      context: "."
    container_name: reddit-clone-celery
    restart: on-failure
    command: poetry run celery -A reddit.tasks worker
    environment:
      DEBUG: "false"
      CELERY_BROKER: amqp://guest:guest@localhost:5672//
      CELERY_BACKEND: redis://localhost:6379
      DATABASE_URL: postgresql+asyncpg://reddit_clone:reddit_clone@db:5432/reddit_clone
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 25
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SENDER:
    depends_on:
      - server
      - rabbitmq
      - redis

volumes:
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local
  postgres-data:
    driver: local
