version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: reddit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: reddit
      POSTGRES_PASSWORD: reddit
      POSTGRES_USER: reddit
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: reddit-redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: reddit
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.9-alpine
    container_name: reddit-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: reddit
      RABBITMQ_DEFAULT_PASS: reddit
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/data

  server:
    build:
      context: "."
    container_name: reddit-server
    restart: unless-stopped
    command: poetry run uvicorn reddit:app --host=0.0.0.0
    environment:
      DEBUG: "false"
      CELERY_BROKER: amqp://reddit:reddit@rabbitmq:5672/
      CELERY_BACKEND: redis://:reddit@localhost:6379/
      DATABASE_URL: postgresql+asyncpg://reddit:reddit@db:5432/reddit
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 25
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SENDER:
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  celery:
    build:
      context: "."
    container_name: reddit-celery
    restart: on-failure
    command: poetry run celery -A reddit.tasks worker
    environment:
      DEBUG: "false"
      CELERY_BROKER: amqp://reddit:reddit@rabbitmq:5672/
      CELERY_BACKEND: redis://:reddit@localhost:6379/
      DATABASE_URL: postgresql+asyncpg://reddit:reddit@db:5432/reddit
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 25
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SENDER:
    depends_on:
      - rabbitmq
      - redis
      - server

volumes:
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local
  postgres-data:
    driver: local
