services:
  database:
    image: postgres:13-alpine
    restart: unless-stopped
    env_file:
      - ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    env_file:
      - ".env"
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3
    env_file:
      - ".env"
    ports:
      - "5672:5672"

  app:
    build:
      context: .
    env_file:
      - ".env"
    depends_on:
      - database

  # celery:
  #   build:
  #     context: .
  #   restart: always
  #   env_file:
  #     - ".env"
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #     - app

volumes:
  postgres-data:
